# Generated by Django 4.2.2 on 2023-07-21 17:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_model',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='main_model',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name=models.TextField()),
        ),
    ]
