# Generated by Django 4.2.2 on 2023-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_main_model_slug_alter_main_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_model',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
